language: bash

dist: bionic

env:
    # Test (in parallel):
    # - with oldest supported docker & docker-compose
    # - with most recent docker & docker-compose
    - DOCKER_COMPOSE_VERSION=1.19.0 DOCKER_VERSION=native
    - DOCKER_COMPOSE_VERSION=1.26.1 DOCKER_VERSION=latest COMPOSE_LOCAL_ENV_FILE=../tests/environment/.env.01.local

#before_install:

install:
    # install docker-compose
    - if [ $DOCKER_COMPOSE_VERSION != native ]; then ./tests/environment/setup/install_docker-compose.sh; fi

    # update to latest docker if required (currently we have 18.06 on the Bionic vm)
    - if [ $DOCKER_VERSION != native ]; then ./tests/environment/setup/install_docker.sh fi

before_script:
    # @todo this could be moved to native functionality of `dbstack`: patch local env file even if it exists
    - echo "CONTAINER_USER_UID=$(id -u)" >> tests/.env.01.local
    - echo "CONTAINER_USER_GID=$(id -g)" >> tests/.env.01.local

script:
    - ./tests/01_smoketest.sh -w 900
    - ./tests/02_dbconsole.sh -w 300
    - ./tests/03_web.sh -w 300
    - ./tests/04_admin.sh -w 300

#after_success:

after_failure:
    #-  if [ -f test01.log ]; then cat test01.log; fi
    #-  if [ -f test02.log ]; then cat test02.log; fi
    #-  if [ -f test03.log ]; then cat test03.log; fi
    #-  if [ -f test04.log ]; then cat test04.log; fi
    - for svc in $(./bin/dbstack services); do docker-compose logs $svc; done

#after_script:
