language: bash

dist: bionic

env:
    # Test (in parallel):
    # - with oldest supported docker & docker-compose
    # - with most recent docker & docker-compose
    - DOCKER_COMPOSE_VERSION=1.10.0 DOCKER_VERSION=native
    - DOCKER_COMPOSE_VERSION=1.25.4 DOCKER_VERSION=latest

#before_install:

install:
    # install docker-compose
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    - docker-compose --version

    # update to latest docker if required (currently we have 18.06 on the Bionic vm)
    - if [ $DOCKER_VERSION = latest ]; then curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -; fi
    - if [ $DOCKER_VERSION = latest ]; then sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"; fi
    - if [ $DOCKER_VERSION = latest ]; then sudo apt-get update; fi
    - if [ $DOCKER_VERSION = latest ]; then sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce; fi
    - if [ $DOCKER_VERSION = latest ]; then docker --version; fi

#before_script:

script:
    - ./tests/01_smoketest.sh
    - ./tests/02_dbconsole.sh
    - ./tests/03_web.sh
    - ./tests/04_admin.sh

#after_success:

after_failure:
    - ./bin/dbstack logs worker

#after_script:
