version: '3'

networks:
    default:
        ipam:
            config:
                - subnet: "${COMPOSE_SUBNET}.0/24"

services:
    web:
        build:
        hostname:
        container_name:
        volumes:
        environment:
        env_file:
    worker:
        build:
            context: images/worker
            args:
                debian_mirror: "${COMPOSE_DEBIAN_MIRROR}"
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
                container_user: "${COMPOSE_CONTAINER_USER}"
        hostname: worker
        container_name: "${COMPOSE_PROJECT_NAME}_worker"
        ports:
            - "3307:3306"
        volumes:
            - ./config/mysql/mysql_${COMPOSE_DB_SIZE}.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./data/mysql/5.6:/var/lib/mysql
            - ./logs/mysql/5.6:/var/log/mysql
        tmpfs:
            # used for mysql temp tables
            - /tmpfs:mode=777,size=1g
        #environment:
        env_file:
            - ./containers.env
            - "$COMPOSE_CONTAINERS_ENV_OVERRIDE_FILE"
    mysql_5_6:
    mysql_5_7:
    mysql_8_0:
    mariadb_10_0:
    mariadb_10_1:
    mariadb_10_2:
    postgres_9_4:
    postgres_9_5:
    postgres_9_6:
    postgres_10_7:
    postgres_11_2: