# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

imports:
    - { resource: '/home/db3v4l/vendors/*.yml' }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

    # this parameter is now defined and filled-in dynamically by a DI Extension
    #db3v4l.database_instances: []

    # @todo allow separate bundles to register database_managers - load this as is done for db3v4l.database_instances
    db3v4l.database_managers:
        # key: vendor name, value: class name
        mariadb: "\\Db3v4l\\Core\\DatabaseManager\\MySQL"
        mssql: "\\Db3v4l\\Core\\DatabaseManager\\SQLServer"
        mysql: "\\Db3v4l\\Core\\DatabaseManager\\MySQL"
        oracle: "\\Db3v4l\\Core\\DatabaseManager\\Oracle"
        percona: "\\Db3v4l\\Core\\DatabaseManager\\MySQL"
        postgresql: "\\Db3v4l\\Core\\DatabaseManager\\PostgreSQL"
        sqlite: "\\Db3v4l\\Core\\DatabaseManager\\SQLite"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Db3v4l\:
        resource: '../src/*'
        exclude: '../src/{API,Core,DependencyInjection,Entity,Migrations,Tests,Util,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Db3v4l\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    db3v4l.database_configuration_manager:
        class: Db3v4l\Service\DatabaseConfigurationManager
        arguments:
            - '%db3v4l.database_instances%'

    Db3v4l\Service\DatabaseConfigurationManager: '@db3v4l.database_configuration_manager'

    db3v4l.database_manager_factory:
        class: Db3v4l\Service\DatabaseManagerFactory
        arguments:
            - '%db3v4l.database_managers%'

    Db3v4l\Service\DatabaseManagerFactory: '@db3v4l.database_manager_factory'

    # manual 'aliasing' of autoconfigured console commands, for the custom console

    db3v4l.dbconsole.collation_list:
        autoconfigure: false
        autowire: true
        class: Db3v4l\Command\CollationList
        tags: ['dbconsole.command']

    db3v4l.dbconsole.database_create:
        autoconfigure: false
        autowire: true
        class: Db3v4l\Command\DatabaseCreate
        tags: ['dbconsole.command']

    db3v4l.dbconsole.database_drop:
        autoconfigure: false
        autowire: true
        class: Db3v4l\Command\DatabaseDrop
        tags: ['dbconsole.command']

    db3v4l.dbconsole.database_list:
        autoconfigure: false
        autowire: true
        class: Db3v4l\Command\DatabaseList
        tags: ['dbconsole.command']

    db3v4l.dbconsole.instance_list:
        autoconfigure: false
        autowire: true
        class: Db3v4l\Command\InstanceList
        tags: ['dbconsole.command']

    db3v4l.dbconsole.sql_execute:
        autoconfigure: false
        autowire: true
        class: Db3v4l\Command\SqlExecute
        tags: ['dbconsole.command']

    db3v4l.dbconsole.sql_shell:
        autoconfigure: false
        autowire: true
        class: Db3v4l\Command\SqlShell
        tags: ['dbconsole.command']

    db3v4l.dbconsole.user_drop:
        autoconfigure: false
        autowire: true
        class: Db3v4l\Command\UserDrop
        tags: ['dbconsole.command']

    db3v4l.dbconsole.user_list:
        autoconfigure: false
        autowire: true
        class: Db3v4l\Command\UserList
        tags: ['dbconsole.command']
