# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

    db3v4l.databases:
        # connection options as used by doctrine
        mariadb_5_5:
            host: mariadb_5_5
            port: 3306
            user: root
            password: 3v4l
            driver: pdo_mysql
            charset: UTF8
            server_version: mariadb-5.5
        mariadb_10_0:
            host: mariadb_10_0
            port: 3306
            user: root
            password: 3v4l
            driver: pdo_mysql
            charset: UTF8
            server_version: mariadb-10.0
        mariadb_10_1:
            host: mariadb_10_1
            port: 3306
            user: root
            password: 3v4l
            driver: pdo_mysql
            charset: UTF8
            server_version: mariadb-10.1
        mariadb_10_2:
            host: mariadb_10_2
            port: 3306
            user: root
            password: 3v4l
            driver: pdo_mysql
            charset: UTF8
            server_version: mariadb-10.2
        mariadb_10_3:
            host: mariadb_10_3
            port: 3306
            user: root
            password: 3v4l
            driver: pdo_mysql
            charset: UTF8
            server_version: mariadb-10.3
        mysql_5_5:
            host: mysql_5_5
            port: 3306
            user: root
            password: 3v4l
            driver: pdo_mysql
            charset: UTF8
            server_version: '5.5'
        mysql_5_6:
            host: mysql_5_6
            port: 3306
            user: root
            password: 3v4l
            driver: pdo_mysql
            charset: UTF8
            server_version: '5.6'
        mysql_5_7:
            host: mysql_5_7
            port: 3306
            user: root
            password: 3v4l
            driver: pdo_mysql
            charset: UTF8
            server_version: '5.7'
        mysql_8_0:
            host: mysql_8_0
            port: 3306
            user: root
            password: 3v4l
            driver: pdo_mysql
            charset: UTF8
            server_version: '8.0'
        postgresql_9_4:
            host: postgresql_9_4
            port: 5432
            user: postgres
            password: 3v4l
            driver: pdo_pgsql
            charset: UTF8
            server_version: '9.4'
        postgresql_9_5:
            host: postgresql_9_5
            port: 5432
            user: postgres
            password: 3v4l
            driver: pdo_pgsql
            charset: UTF8
            server_version: '9.5'
        postgresql_9_6:
            host: postgresql_9_6
            port: 5432
            user: postgres
            password: 3v4l
            driver: pdo_pgsql
            charset: UTF8
            server_version: '9.6'
        postgresql_10_7:
            host: postgresql_10_7
            port: 5432
            user: postgres
            password: 3v4l
            driver: pdo_pgsql
            charset: UTF8
            server_version: '10.7'
        postgresql_11_2:
            host: postgresql_11_2
            port: 5432
            user: postgres
            password: 3v4l
            driver: pdo_pgsql
            charset: UTF8
            server_version: '11.2'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Db3v4l\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Db3v4l\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    db3v4l.database_configuration_manager:
        class: Db3v4l\Service\DatabaseConfigurationManager
        arguments:
            - '%db3v4l.databases%'

    Db3v4l\Service\DatabaseConfigurationManager: '@db3v4l.database_configuration_manager'
