# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

    db3v4l.database_instances:
        # Same format as the connection options used by doctrine for the most part
        # @see https://www.doctrine-project.org/projects/doctrine-dbal/en/2.10/reference/configuration.html#configuration
        # @see \Doctrine\Bundle\DoctrineBundle\DependencyInjection\Configuration::configureDbalDriverNode
        # 'user' = root account for the database instance, should have permissions to create other accounts as well as databases
        mariadb_5_5:
            host: mariadb_5_5
            port: 3306
            user: root
            password: '%env(MYSQL_ROOT_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_mysql
            #server_version: mariadb-5.5
            vendor: mariadb
            version: '5.5'
        mariadb_10_0:
            host: mariadb_10_0
            port: 3306
            user: root
            password: '%env(MYSQL_ROOT_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_mysql
            #server_version: mariadb-10.0
            vendor: mariadb
            version: '10.0'
        mariadb_10_1:
            host: mariadb_10_1
            port: 3306
            user: root
            password: '%env(MYSQL_ROOT_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_mysql
            #server_version: mariadb-10.1
            vendor: mariadb
            version: '10.1'
        mariadb_10_2:
            host: mariadb_10_2
            port: 3306
            user: root
            password: 3v4l
            #charset: UTF8
            #driver: pdo_mysql
            #server_version: mariadb-10.2
            vendor: mariadb
            version: '10.2'
        mariadb_10_3:
            host: mariadb_10_3
            port: 3306
            user: root
            password: 3v4l
            #charset: UTF8
            #driver: pdo_mysql
            #server_version: mariadb-10.3
            vendor: mariadb
            version: '10.3'
        mariadb_10_4:
            host: mariadb_10_4
            port: 3306
            user: root
            password: 3v4l
            charset: UTF8
            #driver: pdo_mysql
            #server_version: mariadb-10.4
            vendor: mariadb
            version: '10.4'
        mssql_2017_cu18:
            host: mssqlserver_2017_cu18
            port: 1433
            user: sa
            password: '%env(SA_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_sqlsrv
            #server_version: ''
            vendor: mssql
            version: '2017.cu18'
        mssql_2019_ga:
            host: mssqlserver_2019_ga
            port: 1433
            user: sa
            password: '%env(SA_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_sqlsrv
            #server_version: ''
            vendor: mssql
            version: '2019.ga'
        mysql_5_5:
            host: mysql_5_5
            port: 3306
            user: root
            password: '%env(MYSQL_ROOT_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_mysql
            #server_version: '5.5'
            vendor: mysql
            version: '5.5'
        mysql_5_6:
            host: mysql_5_6
            port: 3306
            user: root
            password: '%env(MYSQL_ROOT_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_mysql
            #server_version: '5.6'
            vendor: mysql
            version: '5.6'
        mysql_5_7:
            host: mysql_5_7
            port: 3306
            user: root
            password: '%env(MYSQL_ROOT_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_mysql
            #server_version: '5.7'
            vendor: mysql
            version: '5.7'
        mysql_8_0:
            host: mysql_8_0
            port: 3306
            user: root
            password: '%env(MYSQL_ROOT_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_mysql
            #server_version: '8.0'
            vendor: mysql
            version: '8.0'
        percona_5_6:
            host: percona_5_6
            port: 3306
            user: root
            password: '%env(MYSQL_ROOT_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_mysql
            #server_version: '5.6'
            vendor: percona
            version: '5.6'
        percona_5_7:
            host: percona_5_7
            port: 3306
            user: root
            password: '%env(MYSQL_ROOT_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_mysql
            #server_version: '5.7'
            vendor: percona
            version: '5.7'
        percona_8_0:
            host: percona_8_0
            port: 3306
            user: root
            password: '%env(MYSQL_ROOT_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_mysql
            #server_version: '8.0'
            vendor: percona
            version: '8.0'
        oracle_18_4:
            host: oracle_18_4
            port: 1521
            user: system
            password: '%env(ORACLE_PWD)%'
            #charset: UTF8
            #driver: pdo_oci
            #server_version: '18.4'
            servicename: xe
            vendor: oracle
            version: '18.4'
        postgresql_9_4:
            host: postgresql_9_4
            port: 5432
            user: postgres
            password: '%env(POSTGRES_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_pgsql
            #server_version: '9.4'
            vendor: postgresql
            version: '9.4'
        postgresql_9_5:
            host: postgresql_9_5
            port: 5432
            user: postgres
            password: '%env(POSTGRES_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_pgsql
            #server_version: '9.5'
            vendor: postgresql
            version: '9.5'
        postgresql_9_6:
            host: postgresql_9_6
            port: 5432
            user: postgres
            password: 3v4l
            #charset: UTF8
            #driver: pdo_pgsql
            #server_version: '9.6'
            vendor: postgresql
            version: '9.6'
        postgresql_10_11:
            host: postgresql_10_11
            port: 5432
            user: postgres
            password: '%env(POSTGRES_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_pgsql
            #server_version: '10.11'
            vendor: postgresql
            version: '10.11'
        postgresql_11_6:
            host: postgresql_11_6
            port: 5432
            user: postgres
            password: '%env(POSTGRES_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_pgsql
            #server_version: '11.6'
            vendor: postgresql
            version: '11.6'
        postgresql_12_1:
            host: postgresql_12_1
            port: 5432
            user: postgres
            password: '%env(POSTGRES_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_pgsql
            #server_version: '12.1'
            vendor: postgresql
            version: '12.1'
        sqlite_3_27:
            driver: pdo_sqlite
            path: /home/db3v4l/data/sqlite/3.27/3v4l.sqlite
            vendor: sqlite
            version: '3.27'

    db3v4l.database_managers:
        # key: vendor name, value: class name
        mariadb: "\\Db3v4l\\Core\\DatabaseManager\\MySQL"
        mssql: "\\Db3v4l\\Core\\DatabaseManager\\SQLServer"
        mysql: "\\Db3v4l\\Core\\DatabaseManager\\MySQL"
        oracle: "\\Db3v4l\\Core\\DatabaseManager\\Oracle12"
        percona: "\\Db3v4l\\Core\\DatabaseManager\\MySQL"
        postgresql: "\\Db3v4l\\Core\\DatabaseManager\\PostgreSQL"
        sqlite: "\\Db3v4l\\Core\\DatabaseManager\\SQLite"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Db3v4l\:
        resource: '../src/*'
        exclude: '../src/{API,Core,DependencyInjection,Entity,Migrations,Tests,Util,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Db3v4l\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    db3v4l.database_configuration_manager:
        class: Db3v4l\Service\DatabaseConfigurationManager
        arguments:
            - '%db3v4l.database_instances%'

    Db3v4l\Service\DatabaseConfigurationManager: '@db3v4l.database_configuration_manager'

    db3v4l.database_manager_factory:
        class: Db3v4l\Service\DatabaseManagerFactory
        arguments:
            - '%db3v4l.database_managers%'

    Db3v4l\Service\DatabaseManagerFactory: '@db3v4l.database_manager_factory'

    # manual 'aliasing' of autoconfigured console commands, for the custom console

    db3v4l.dbconsole.collation_list:
        autoconfigure: false
        autowire: true
        class: Db3v4l\Command\CollationList
        tags: ['dbconsole.command']

    db3v4l.dbconsole.database_create:
        autoconfigure: false
        autowire: true
        class: Db3v4l\Command\DatabaseCreate
        tags: ['dbconsole.command']

    db3v4l.dbconsole.database_drop:
        autoconfigure: false
        autowire: true
        class: Db3v4l\Command\DatabaseDrop
        tags: ['dbconsole.command']

    db3v4l.dbconsole.database_list:
        autoconfigure: false
        autowire: true
        class: Db3v4l\Command\DatabaseList
        tags: ['dbconsole.command']

    db3v4l.dbconsole.instance_list:
        autoconfigure: false
        autowire: true
        class: Db3v4l\Command\InstanceList
        tags: ['dbconsole.command']

    db3v4l.dbconsole.sql_execute:
        autoconfigure: false
        autowire: true
        class: Db3v4l\Command\SqlExecute
        tags: ['dbconsole.command']

    db3v4l.dbconsole.sql_shell:
        autoconfigure: false
        autowire: true
        class: Db3v4l\Command\SqlShell
        tags: ['dbconsole.command']

    db3v4l.dbconsole.user_drop:
        autoconfigure: false
        autowire: true
        class: Db3v4l\Command\UserDrop
        tags: ['dbconsole.command']

    db3v4l.dbconsole.user_list:
        autoconfigure: false
        autowire: true
        class: Db3v4l\Command\UserList
        tags: ['dbconsole.command']
