version: '3'

networks:
    default:
        ipam:
            config:
                - subnet: "${COMPOSE_SUBNET}.0/24"

services:

    web:
        build:
            context: images/web
            args:
                debian_mirror: "${COMPOSE_DEBIAN_MIRROR}"
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
        hostname: web
        container_name: "${COMPOSE_PROJECT_NAME}_web"
        ports:
            - "${COMPOSE_WEB_LISTEN_ADDR}:${COMPOSE_WEB_LISTEN_PORT_HTTP}:80"
            - "${COMPOSE_WEB_LISTEN_ADDR}:${COMPOSE_WEB_LISTEN_PORT_HTTPS}:443"
        volumes:
            - ../app:/var/www/db3v4l
            - ../doc:/var/www/doc
            - ./logs/web/nginx:/var/log/nginx
            - ./logs/web/php:/var/log/php
        environment:
            - CONTAINER_USER
        env_file:
            - ./containers.env
            - "${COMPOSE_CONTAINERS_ENV_OVERRIDE_FILE}"

    admin:
        build:
            context: images/admin
            args:
                debian_mirror: "${COMPOSE_DEBIAN_MIRROR}"
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
        hostname: admin
        container_name: "${COMPOSE_PROJECT_NAME}_admin"
        # No ports exposed by default: we use the 'web' container as reverse proxy
        #ports:
        #    - "${COMPOSE_WEB_LISTEN_ADDR}:${COMPOSE_WEB_LISTEN_PORT_HTTP}:80"
        #    - "${COMPOSE_WEB_LISTEN_ADDR}:${COMPOSE_WEB_LISTEN_PORT_HTTPS}:443"
        volumes:
            - ../app:/var/www/db3v4l
            - ./logs/admin/nginx:/var/log/nginx
            - ./logs/admin/php:/var/log/php
        environment:
            - CONTAINER_USER
        env_file:
            - ./containers.env
            - "${COMPOSE_CONTAINERS_ENV_OVERRIDE_FILE}"
    worker:
        build:
            context: images/worker
            args:
                debian_mirror: "${COMPOSE_DEBIAN_MIRROR}"
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
                container_user: "${CONTAINER_USER}"
        hostname: worker
        container_name: "${COMPOSE_PROJECT_NAME}_worker"
        volumes:
            - "../app:/home/${CONTAINER_USER}/app"
            - "../doc:/home/${CONTAINER_USER}/doc"
            - "../shared:/home/${CONTAINER_USER}/shared"
            - "./data/composer_cache/:/home/${CONTAINER_USER}/.composer"
            - "./data/sqlite/:/home/${CONTAINER_USER}/data/sqlite"
        environment:
            - CONTAINER_USER
            - COMPOSE_SETUP_APP_ON_BUILD
        env_file:
            - ./containers.env
            - "${COMPOSE_CONTAINERS_ENV_OVERRIDE_FILE}"

    mysql_5_5:
        build:
            context: images/mysql/5.5
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
        hostname: mysql_5_5
        container_name: "${COMPOSE_PROJECT_NAME}_mysql_5_5"
        #ports:
        #    - "3306:3306"
        volumes:
            - ./config/mysql/5.5/${COMPOSE_DB_SIZE}.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./data/mysql/5.5:/var/lib/mysql
            - ./logs/mysql/5.5:/var/log/mysql
        tmpfs:
            # used for mysql temp tables
            - /tmpfs:mode=777,size=1g
        environment:
            - CONTAINER_USER
        env_file:
            - ./containers.env
            - "${COMPOSE_CONTAINERS_ENV_OVERRIDE_FILE}"

    mysql_5_6:
        build:
            context: images/mysql/5.6
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
        hostname: mysql_5_6
        container_name: "${COMPOSE_PROJECT_NAME}_mysql_5_6"
        #ports:
        #    - "3307:3306"
        volumes:
            - ./config/mysql/5.6/${COMPOSE_DB_SIZE}.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./data/mysql/5.6:/var/lib/mysql
            - ./logs/mysql/5.6:/var/log/mysql
        tmpfs:
            # used for mysql temp tables
            - /tmpfs:mode=777,size=1g
        environment:
            - CONTAINER_USER
        env_file:
            - ./containers.env
            - "${COMPOSE_CONTAINERS_ENV_OVERRIDE_FILE}"

    mysql_5_7:
        build:
            context: images/mysql/5.7
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
        hostname: mysql_5_7
        container_name: "${COMPOSE_PROJECT_NAME}_mysql_5_7"
        #ports:
        #    - "3308:3306"
        volumes:
            - ./config/mysql/5.7/${COMPOSE_DB_SIZE}.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./data/mysql/5.7:/var/lib/mysql
            - ./logs/mysql/5.7:/var/log/mysql
        tmpfs:
            # used for mysql temp tables
            - /tmpfs:mode=777,size=1g
        environment:
            - CONTAINER_USER
        env_file:
            - ./containers.env
            - "${COMPOSE_CONTAINERS_ENV_OVERRIDE_FILE}"

    mysql_8_0:
        build:
            context: images/mysql/8.0
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
        hostname: mysql_8_0
        container_name: "${COMPOSE_PROJECT_NAME}_mysql_8_0"
        #ports:
        #    - "3309:3306"
        volumes:
            - ./config/mysql/8.0/${COMPOSE_DB_SIZE}.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./data/mysql/8.0:/var/lib/mysql
            - ./logs/mysql/8.0:/var/log/mysql
        tmpfs:
            # used for mysql temp tables
            - /tmpfs:mode=777,size=1g
        environment:
            - CONTAINER_USER
        env_file:
            - ./containers.env
            - "${COMPOSE_CONTAINERS_ENV_OVERRIDE_FILE}"

    mariadb_5_5:
        build:
            context: images/mariadb/5.5
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
        hostname: mariadb_5_5
        container_name: "${COMPOSE_PROJECT_NAME}_mariadb_5_5"
        #ports:
        #    - "3310:3306"
        volumes:
            - ./config/mariadb/5.5/${COMPOSE_DB_SIZE}.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./data/mariadb/5.5:/var/lib/mysql
            - ./logs/mariadb/5.5:/var/log/mysql
        tmpfs:
            # used for mysql temp tables
            - /tmpfs:mode=777,size=1g
        environment:
            - CONTAINER_USER
        env_file:
            - ./containers.env
            - "${COMPOSE_CONTAINERS_ENV_OVERRIDE_FILE}"

    mariadb_10_0:
        build:
            context: images/mariadb/10.0
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
        hostname: mariadb_10_0
        container_name: "${COMPOSE_PROJECT_NAME}_mariadb_10_0"
        #ports:
        #    - "3311:3306"
        volumes:
            - ./config/mariadb/10.0/${COMPOSE_DB_SIZE}.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./data/mariadb/10.0:/var/lib/mysql
            - ./logs/mariadb/10.0:/var/log/mysql
        tmpfs:
            # used for mysql temp tables
            - /tmpfs:mode=777,size=1g
        environment:
            - CONTAINER_USER
        env_file:
            - ./containers.env
            - "${COMPOSE_CONTAINERS_ENV_OVERRIDE_FILE}"

    mariadb_10_1:
        build:
            context: images/mariadb/10.1
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
        hostname: mariadb_10_1
        container_name: "${COMPOSE_PROJECT_NAME}_mariadb_10_1"
        #ports:
        #    - "3312:3306"
        volumes:
            - ./config/mariadb/10.1/${COMPOSE_DB_SIZE}.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./data/mariadb/10.1:/var/lib/mysql
            - ./logs/mariadb/10.1:/var/log/mysql
        tmpfs:
            # used for mysql temp tables
            - /tmpfs:mode=777,size=1g
        environment:
            - CONTAINER_USER
        env_file:
            - ./containers.env
            - "${COMPOSE_CONTAINERS_ENV_OVERRIDE_FILE}"

    mariadb_10_2:
        build:
            context: images/mariadb/10.2
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
        hostname: mariadb_10_2
        container_name: "${COMPOSE_PROJECT_NAME}_mariadb_10_2"
        #ports:
        #    - "3313:3306"
        volumes:
            - ./config/mariadb/10.2/${COMPOSE_DB_SIZE}.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./data/mariadb/10.2:/var/lib/mysql
            - ./logs/mariadb/10.2:/var/log/mysql
        tmpfs:
            # used for mysql temp tables
            - /tmpfs:mode=777,size=1g
        environment:
            - CONTAINER_USER
        env_file:
            - ./containers.env
            - "${COMPOSE_CONTAINERS_ENV_OVERRIDE_FILE}"

    mariadb_10_3:
        build:
            context: images/mariadb/10.3
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
        hostname: mariadb_10_3
        container_name: "${COMPOSE_PROJECT_NAME}_mariadb_10_3"
        #ports:
        #    - "3314:3306"
        volumes:
            - ./config/mariadb/10.3/${COMPOSE_DB_SIZE}.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./data/mariadb/10.3:/var/lib/mysql
            - ./logs/mariadb/10.3:/var/log/mysql
        tmpfs:
            # used for mysql temp tables
            - /tmpfs:mode=777,size=1g
        environment:
            - CONTAINER_USER
        env_file:
            - ./containers.env
            - "${COMPOSE_CONTAINERS_ENV_OVERRIDE_FILE}"

    mariadb_10_4:
        build:
            context: images/mariadb/10.4
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
        hostname: mariadb_10_4
        container_name: "${COMPOSE_PROJECT_NAME}_mariadb_10_4"
        #ports:
        #    - "3315:3306"
        volumes:
            - ./config/mariadb/10.4/${COMPOSE_DB_SIZE}.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./data/mariadb/10.4:/var/lib/mysql
            - ./logs/mariadb/10.4:/var/log/mysql
        tmpfs:
            # used for mysql temp tables
            - /tmpfs:mode=777,size=1g
        environment:
            - CONTAINER_USER
        env_file:
            - ./containers.env
            - "${COMPOSE_CONTAINERS_ENV_OVERRIDE_FILE}"

    mssqlserver_2017_cu17:
        build:
            context: images/mssqlserver/2017.cu17
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
        hostname:  mssqlserver_2017_cu17
        container_name: "${COMPOSE_PROJECT_NAME}_mssqlserver_2017_cu17"
        #ports:
        #    - "1433:1433"
        volumes:
            - ./config/mssqlserver/2017.cu17/${COMPOSE_DB_SIZE}.conf:/var/opt/mssql/mssql.conf
            - ./data/mssqlserver/2017.cu17:/var/opt/mssql/data
            - ./logs/mssqlserver/2017.cu17:/var/opt/mssql/log
        #tmpfs:
        #    # used for mysql temp tables
        #    - /tmpfs:mode=777,size=1g
        environment:
            - CONTAINER_USER
        env_file:
            - ./containers.env
            - "${COMPOSE_CONTAINERS_ENV_OVERRIDE_FILE}"

    mssqlserver_2019_ga:
        build:
            context: images/mssqlserver/2019.ga
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
        hostname:  mssqlserver_2019_ga
        container_name: "${COMPOSE_PROJECT_NAME}_mssqlserver_2019_ga"
        #ports:
        #    - "1434:1433"
        volumes:
            - ./config/mssqlserver/2019.ga/${COMPOSE_DB_SIZE}.conf:/var/opt/mssql/mssql.conf
            - ./data/mssqlserver/2019.ga:/var/opt/mssql/data
            - ./logs/mssqlserver/2019.ga:/var/opt/mssql/log
        #tmpfs:
        #    # used for mysql temp tables
        #    - /tmpfs:mode=777,size=1g
        environment:
            - CONTAINER_USER
        env_file:
            - ./containers.env
            - "${COMPOSE_CONTAINERS_ENV_OVERRIDE_FILE}"

    # oracle...

    postgresql_9_4:
        build:
            context: images/postgresql/9.4
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
        hostname: postgresql_9_4
        container_name: "${COMPOSE_PROJECT_NAME}_postgresql_9_4"
        #ports:
        #    - "5432:5432"
        volumes:
            - ./config/postgresql/9.4/${COMPOSE_DB_SIZE}.conf:/etc/postgresql/conf.d/postgresql.conf
            - ./data/postgresql/9.4:/var/lib/postgresql
            - ./logs/postgresql/9.4:/var/log/postgresql
        environment:
            - CONTAINER_USER
        env_file:
            - ./containers.env
            - "${COMPOSE_CONTAINERS_ENV_OVERRIDE_FILE}"

    postgresql_9_5:
        build:
            context: images/postgresql/9.5
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
        hostname: postgresql_9_5
        container_name: "${COMPOSE_PROJECT_NAME}_postgresql_9_5"
        #ports:
        #    - "5433:5432"
        volumes:
            - ./config/postgresql/9.5/${COMPOSE_DB_SIZE}.conf:/etc/postgresql/conf.d/postgresql.conf
            - ./data/postgresql/9.5:/var/lib/postgresql
            - ./logs/postgresql/9.5:/var/log/postgresql
        environment:
            - CONTAINER_USER
        env_file:
            - ./containers.env
            - "${COMPOSE_CONTAINERS_ENV_OVERRIDE_FILE}"

    postgresql_9_6:
        build:
            context: images/postgresql/9.6
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
        hostname: postgresql_9_6
        container_name: "${COMPOSE_PROJECT_NAME}_postgresql_9_6"
        #ports:
        #    - "5434:5432"
        volumes:
            - ./config/postgresql/9.6/${COMPOSE_DB_SIZE}.conf:/etc/postgresql/conf.d/postgresql.conf
            - ./data/postgresql/9.6:/var/lib/postgresql
            - ./logs/postgresql/9.6:/var/log/postgresql
        environment:
            - CONTAINER_USER
        env_file:
            - ./containers.env
            - "${COMPOSE_CONTAINERS_ENV_OVERRIDE_FILE}"

    postgresql_10_11:
        build:
            context: images/postgresql/10.11
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
        hostname: postgresql_10_11
        container_name: "${COMPOSE_PROJECT_NAME}_postgresql_10_11"
        #ports:
        #    - "5435:5432"
        volumes:
            - ./config/postgresql/10.11/${COMPOSE_DB_SIZE}.conf:/etc/postgresql/conf.d/postgresql.conf
            - ./data/postgresql/10.11:/var/lib/postgresql
            - ./logs/postgresql/10.11:/var/log/postgresql
        environment:
            - CONTAINER_USER
        env_file:
            - ./containers.env
            - "${COMPOSE_CONTAINERS_ENV_OVERRIDE_FILE}"

    postgresql_11_6:
        build:
            context: images/postgresql/11.6
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
        hostname: postgresql_11_6
        container_name: "${COMPOSE_PROJECT_NAME}_postgresql_11_6"
        #ports:
        #    - "5436:5432"
        volumes:
            - ./config/postgresql/11.6/${COMPOSE_DB_SIZE}.conf:/etc/postgresql/conf.d/postgresql.conf
            - ./data/postgresql/11.6:/var/lib/postgresql
            - ./logs/postgresql/11.6:/var/log/postgresql
        environment:
            - CONTAINER_USER
        env_file:
            - ./containers.env
            - "${COMPOSE_CONTAINERS_ENV_OVERRIDE_FILE}"

    postgresql_12_1:
        build:
            context: images/postgresql/12.1
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
        hostname: postgresql_12_1
        container_name: "${COMPOSE_PROJECT_NAME}_postgresql_12_1"
        #ports:
        #    - "5437:5432"
        volumes:
            - ./config/postgresql/12.1/${COMPOSE_DB_SIZE}.conf:/etc/postgresql/conf.d/postgresql.conf
            - ./data/postgresql/12.1:/var/lib/postgresql
            - ./logs/postgresql/12.1:/var/log/postgresql
        environment:
            - CONTAINER_USER
        env_file:
            - ./containers.env
            - "${COMPOSE_CONTAINERS_ENV_OVERRIDE_FILE}"
