SET QUOTED_IDENTIFIER ON;
CREATE DATABASE "plutq";
CREATE LOGIN "plutq" WITH PASSWORD = 'plutq', DEFAULT_DATABASE = "plutq", CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF;
GO
USE "plutq";
CREATE USER "plutq" FOR LOGIN "plutq";
--GRANT ALL TO "plutq";
 ALTER ROLE db_owner ADD MEMBER "plutq";
