db3v4l:
    database_instances:
        # Same format as the connection options used by doctrine for the most part
        # @see https://www.doctrine-project.org/projects/doctrine-dbal/en/2.10/reference/configuration.html#configuration
        # @see \Doctrine\Bundle\DoctrineBundle\DependencyInjection\Configuration::configureDbalDriverNode
        # 'user' = root account for the database instance, should have permissions to create other accounts as well as databases
        mariadb_5_5:
            host: mariadb_5_5
            port: 3306
            user: root
            password: '%env(MYSQL_ROOT_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_mysql
            #server_version: mariadb-5.5
            vendor: mariadb
            version: '5.5'
        mariadb_10_0:
            host: mariadb_10_0
            port: 3306
            user: root
            password: '%env(MYSQL_ROOT_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_mysql
            #server_version: mariadb-10.0
            vendor: mariadb
            version: '10.0'
        mariadb_10_1:
            host: mariadb_10_1
            port: 3306
            user: root
            password: '%env(MYSQL_ROOT_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_mysql
            #server_version: mariadb-10.1
            vendor: mariadb
            version: '10.1'
        mariadb_10_2:
            host: mariadb_10_2
            port: 3306
            user: root
            password: '%env(MYSQL_ROOT_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_mysql
            #server_version: mariadb-10.2
            vendor: mariadb
            version: '10.2'
        mariadb_10_3:
            host: mariadb_10_3
            port: 3306
            user: root
            password: '%env(MYSQL_ROOT_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_mysql
            #server_version: mariadb-10.3
            vendor: mariadb
            version: '10.3'
        mariadb_10_4:
            host: mariadb_10_4
            port: 3306
            user: root
            password: '%env(MYSQL_ROOT_PASSWORD)%'
            charset: UTF8
            #driver: pdo_mysql
            #server_version: mariadb-10.4
            vendor: mariadb
            version: '10.4'
        mariadb_10_5:
            host: mariadb_10_5
            port: 3306
            user: root
            password: '%env(MYSQL_ROOT_PASSWORD)%'
            charset: UTF8
            #driver: pdo_mysql
            #server_version: mariadb-10.4
            vendor: mariadb
            version: '10.5'
