db3v4l:
    database_instances:
        # Same format as the connection options used by doctrine for the most part
        # @see https://www.doctrine-project.org/projects/doctrine-dbal/en/2.10/reference/configuration.html#configuration
        # @see \Doctrine\Bundle\DoctrineBundle\DependencyInjection\Configuration::configureDbalDriverNode
        # 'user' = root account for the database instance, should have permissions to create other accounts as well as databases
        mssql_2017:
            host: mssqlserver_2017
            port: 1433
            user: sa
            password: '%env(SA_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_sqlsrv
            #server_version: ''
            vendor: mssql
            version: '2017'
        mssql_2019:
            host: mssqlserver_2019
            port: 1433
            user: sa
            password: '%env(SA_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_sqlsrv
            #server_version: ''
            vendor: mssql
            version: '2019'
