db3v4l:
    database_instances:
        # Same format as the connection options used by doctrine for the most part
        # @see https://www.doctrine-project.org/projects/doctrine-dbal/en/2.10/reference/configuration.html#configuration
        # @see \Doctrine\Bundle\DoctrineBundle\DependencyInjection\Configuration::configureDbalDriverNode
        # 'user' = root account for the database instance, should have permissions to create other accounts as well as databases
        mysql_5_5:
            host: mysql_5_5
            port: 3306
            user: root
            password: '%env(MYSQL_ROOT_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_mysql
            #server_version: '5.5'
            vendor: mysql
            version: '5.5'
        mysql_5_6:
            host: mysql_5_6
            port: 3306
            user: root
            password: '%env(MYSQL_ROOT_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_mysql
            #server_version: '5.6'
            vendor: mysql
            version: '5.6'
        mysql_5_7:
            host: mysql_5_7
            port: 3306
            user: root
            password: '%env(MYSQL_ROOT_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_mysql
            #server_version: '5.7'
            vendor: mysql
            version: '5.7'
        mysql_8_0:
            host: mysql_8_0
            port: 3306
            user: root
            password: '%env(MYSQL_ROOT_PASSWORD)%'
            #charset: UTF8
            #driver: pdo_mysql
            #server_version: '8.0'
            vendor: mysql
            version: '8.0'
