db3v4l:
    database_instances:
        # Same format as the connection options used by doctrine for the most part
        # @see https://www.doctrine-project.org/projects/doctrine-dbal/en/2.10/reference/configuration.html#configuration
        # @see \Doctrine\Bundle\DoctrineBundle\DependencyInjection\Configuration::configureDbalDriverNode
        # 'user' = root account for the database instance, should have permissions to create other accounts as well as databases
        oracle_18_4:
            host: oracle_18_4
            port: 1521
            user: sys
            password: '%env(ORACLE_PWD)%'
            #charset: UTF8
            #driver: pdo_oci
            #server_version: '18.4'
            # We work inside the pdb 1 by default. It makes it easier to create users with any name...
            servicename: xepdb1
            vendor: oracle
            version: '18.4'
