db3v4l:
    database_instances:
        # Same format as the connection options used by doctrine for the most part
        # @see https://www.doctrine-project.org/projects/doctrine-dbal/en/2.10/reference/configuration.html#configuration
        # @see \Doctrine\Bundle\DoctrineBundle\DependencyInjection\Configuration::configureDbalDriverNode
        # 'user' = root account for the database instance, should have permissions to create other accounts as well as databases
        sqlite_3_27:
            driver: pdo_sqlite
            path: /home/db3v4l/data/sqlite/3.27/3v4l.sqlite
            vendor: sqlite
            version: '3.27'
