version: '3'

services:

    worker:
        volumes:
            - ./config/app/mssql.yml:/home/${CONTAINER_USER}/vendors/mssql.yml
        environment:
            - SA_PASSWORD
    web:
        volumes:
            - ./config/app/mssql.yml:/home/${CONTAINER_USER}/vendors/mssql.yml
    adminer:
        volumes:
            - ./config/app/mssql.yml:/var/www/vendors/mssql.yml
        environment:
            - SA_PASSWORD

    mssqlserver_2017:
        build:
            context: images/mssqlserver/2017
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
                do_shrink_container: "${COMPOSE_DO_SHRINK_CONTAINERS}"
                base_image_version: "${MSSQLSERVER_2017_VERSION}"
        hostname:  mssqlserver_2017
        container_name: "${COMPOSE_PROJECT_NAME}_mssqlserver_2017"
        #ports:
        #    - "1433:1433"
        volumes:
            - ./config/mssqlserver/2017/${COMPOSE_DB_SIZE}.conf:/var/opt/mssql/mssql.conf
            - ./data/mssqlserver/2017:/var/opt/mssql/data
            - ./logs/mssqlserver/2017:/var/opt/mssql/log
        #tmpfs:
        #    # used for mysql temp tables
        #    - /tmpfs:mode=777,size=1g
        environment:
            - CONTAINER_USER_UID
            - CONTAINER_USER_GID
            - ACCEPT_EULA
            - SA_PASSWORD

    mssqlserver_2019:
        build:
            context: images/mssqlserver/2019
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
                do_shrink_container: "${COMPOSE_DO_SHRINK_CONTAINERS}"
                base_image_version: "${MSSQLSERVER_2019_VERSION}"
        hostname:  mssqlserver_2019
        container_name: "${COMPOSE_PROJECT_NAME}_mssqlserver_2019"
        #ports:
        #    - "1434:1433"
        volumes:
            - ./config/mssqlserver/2019/${COMPOSE_DB_SIZE}.conf:/var/opt/mssql/mssql.conf
            - ./data/mssqlserver/2019:/var/opt/mssql/data
            - ./logs/mssqlserver/2019:/var/opt/mssql/log
        #tmpfs:
        #    # used for mysql temp tables
        #    - /tmpfs:mode=777,size=1g
        environment:
            - CONTAINER_USER_UID
            - CONTAINER_USER_GID
            - ACCEPT_EULA
            - SA_PASSWORD
