version: '3'

services:

    worker:
        volumes:
            - ./config/app/mysql.yml:/home/${CONTAINER_USER}/vendors/mysql.yml
        environment:
            - MYSQL_ROOT_PASSWORD
    web:
        volumes:
            - ./config/app/mysql.yml:/home/${CONTAINER_USER}/vendors/mysql.yml
    adminer:
        volumes:
            - ./config/app/mysql.yml:/var/www/vendors/mysql.yml
        environment:
            - MYSQL_ROOT_PASSWORD

    mysql_5_5:
        build:
            context: images/mysql/5.5
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
                do_shrink_container: "${COMPOSE_DO_SHRINK_CONTAINERS}"
                base_image_version: "${MYSQL_5_5_VERSION}"
        hostname: mysql_5_5
        container_name: "${COMPOSE_PROJECT_NAME}_mysql_5_5"
        #ports:
        #    - "3306:3306"
        volumes:
            - ./config/mysql/5.5/${COMPOSE_DB_SIZE}.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./data/mysql/5.5:/var/lib/mysql
            - ./logs/mysql/5.5:/var/log/mysql
        tmpfs:
            # used for mysql temp tables
            - /tmpfs:mode=777,size=1g
        environment:
            - CONTAINER_USER_UID
            - CONTAINER_USER_GID
            - MYSQL_ROOT_PASSWORD
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_DATABASE

    mysql_5_6:
        build:
            context: images/mysql/5.6
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
                do_shrink_container: "${COMPOSE_DO_SHRINK_CONTAINERS}"
                base_image_version: "${MYSQL_5_6_VERSION}"
        hostname: mysql_5_6
        container_name: "${COMPOSE_PROJECT_NAME}_mysql_5_6"
        #ports:
        #    - "3307:3306"
        volumes:
            - ./config/mysql/5.6/${COMPOSE_DB_SIZE}.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./data/mysql/5.6:/var/lib/mysql
            - ./logs/mysql/5.6:/var/log/mysql
        tmpfs:
            # used for mysql temp tables
            - /tmpfs:mode=777,size=1g
        environment:
            - CONTAINER_USER_UID
            - CONTAINER_USER_GID
            - MYSQL_ROOT_PASSWORD
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_DATABASE

    mysql_5_7:
        build:
            context: images/mysql/5.7
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
                do_shrink_container: "${COMPOSE_DO_SHRINK_CONTAINERS}"
                base_image_version: "${MYSQL_5_7_VERSION}"
        hostname: mysql_5_7
        container_name: "${COMPOSE_PROJECT_NAME}_mysql_5_7"
        #ports:
        #    - "3308:3306"
        volumes:
            - ./config/mysql/5.7/${COMPOSE_DB_SIZE}.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./data/mysql/5.7:/var/lib/mysql
            - ./logs/mysql/5.7:/var/log/mysql
        tmpfs:
            # used for mysql temp tables
            - /tmpfs:mode=777,size=1g
        environment:
            - CONTAINER_USER_UID
            - CONTAINER_USER_GID
            - MYSQL_ROOT_PASSWORD
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_DATABASE

    mysql_8_0:
        build:
            context: images/mysql/8.0
            args:
                timezone: "${COMPOSE_TZ}"
                do_update_os: "${COMPOSE_DO_UPDATE_OS}"
                do_shrink_container: "${COMPOSE_DO_SHRINK_CONTAINERS}"
                base_image_version: "${MYSQL_8_0_VERSION}"
        hostname: mysql_8_0
        container_name: "${COMPOSE_PROJECT_NAME}_mysql_8_0"
        #ports:
        #    - "3309:3306"
        volumes:
            - ./config/mysql/8.0/${COMPOSE_DB_SIZE}.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./data/mysql/8.0:/var/lib/mysql
            - ./logs/mysql/8.0:/var/log/mysql
        tmpfs:
            # used for mysql temp tables
            - /tmpfs:mode=777,size=1g
        environment:
            - CONTAINER_USER_UID
            - CONTAINER_USER_GID
            - MYSQL_ROOT_PASSWORD
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_DATABASE
